# TODOs:
# add in loc
# need to rebase off main to get latest DLL namings
# Signing needs to work

# This build should never run as CI or against a pull request.
trigger: none
pr: none

pool: 
  name: WinDevPool-L
  demands: ImageOverride -equals WinDevVS16-latest

parameters:
  - name: buildConfigurations
    type: object
    default:
      - Release
  - name: buildPlatforms
    type: object
    default:
      - x64

name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Build
  strategy:
    matrix:
      ${{ each config in parameters.buildConfigurations }}:
        ${{ each platform in parameters.buildPlatforms }}:
          ${{ config }}_${{ platform }}:
            BuildConfiguration: ${{ config }}
            BuildPlatform: ${{ platform }}
  displayName: Build
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    submodules: true
    persistCredentials: True

  - task: CopyFiles@2
    displayName: test output
    inputs: 
      sourceFolder: './src'
      Contents: >-
        'readme.md'
      TargetFolder: Build_Output
      OverWrite: true

#  - task: PkgESSetupBuild@12
#    displayName: Package ES - Setup Build
#    inputs:
#      disableOutputRedirect: true
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 5.10
    inputs:
      versionSpec: 5.10
  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: PowerToysCDPxFeed

# this will do the following:
# - main solution
# - Bug report tool
# - Webcam report tool
# - Installer
# - Bootstrapper Installer
  - task: NuGetCommand@2
    displayName: NuGet restore solutions dependencies
    inputs:
      command: restore
      restoreSolution: '**/*.sln'
      selectOrConfig: config
      nugetConfigPath: .pipelines/release-nuget.config
      
  - task: CmdLine@2
    displayName: Moving telem files over
    inputs:
      script: |
        call nuget.exe restore -configFile .pipelines/release-nuget.config -PackagesDirectory . .pipelines/packages.config || exit /b 1
        move /Y "Microsoft.PowerToys.Telemetry.2.0.0\build\include\TraceLoggingDefines.h" "src\common\Telemetry\TraceLoggingDefines.h" || exit /b 1
        move /Y "Microsoft.PowerToys.Telemetry.2.0.0\build\include\TelemetryBase.cs" "src\common\Telemetry\TelemetryBase.cs" || exit /b 1
    
#  - task: TouchdownBuildTask@1
#    displayName: Download Localization Files
#    inputs:
#      teamId: 7105
#      authId: $(TouchdownAppId)
#      authKey: $(TouchdownAppKey)
#      resourceFilePath: >-
#        src\cascadia\TerminalApp\Resources\en-US\Resources.resw
#
#        src\cascadia\TerminalControl\Resources\en-US\Resources.resw
#
#        src\cascadia\TerminalConnection\Resources\en-US\Resources.resw
#
#        src\cascadia\TerminalSettingsModel\Resources\en-US\Resources.resw
#
#        src\cascadia\TerminalSettingsEditor\Resources\en-US\Resources.resw
#
#        src\cascadia\WindowsTerminalUniversal\Resources\en-US\Resources.resw
#
#        src\cascadia\CascadiaPackage\Resources\en-US\Resources.resw
#      appendRelativeDir: true
#      localizationTarget: false
#      pseudoSetting: Included
#  - task: PowerShell@2
#    displayName: Move Loc files one level up
#    inputs:
#      targetType: inline
#      script: >-
#        $Files = Get-ChildItem . -R -Filter 'Resources.resw' | ? FullName -Like '*en-US\*\Resources.resw'
#
#        $Files | % { Move-Item -Verbose $_.Directory $_.Directory.Parent.Parent -EA:Ignore }
#      pwsh: true
  - task: VSBuild@1
    displayName: Build PowerToys main project
    inputs:
      solution: '**\PowerToys.sln'
      vsVersion: 16.0
      msbuildArgs: /p:CIBuild=true /bl:$(Build.SourcesDirectory)\msbuild.binlog
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
      maximumCpuCount: true

  - task: VSBuild@1
    displayName: Build BugReportTool
    inputs:
      solution: '**/tools/BugReportTool/BugReportTool.sln'
      vsVersion: 16.0
      msbuildArgs: /p:CIBuild=true /bl:$(Build.SourcesDirectory)\msbuild.binlog
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
      maximumCpuCount: true

  - task: VSBuild@1
    displayName: Build WebcamReportTool
    inputs:
      solution: '**/tools/WebcamReportTool/WebcamReportTool.sln'
      vsVersion: 16.0
      msbuildArgs: /p:CIBuild=true /bl:$(Build.SourcesDirectory)\msbuild.binlog
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
      maximumCpuCount: true

# 1st PARTY FILES FILES NEED TO BE SIGNED HERE
# 3rd PARTY FILES FILES NEED TO BE SIGNED HERE

  - task: VSBuild@1
    displayName: Build PowerToysSetup PowerToysSetupCustomActions
    inputs:
      solution: '**/installer/PowerToysSetup.sln'
      vsVersion: 16.0
      msbuildArgs: /target:PowerToysSetupCustomActions /p:CIBuild=true /bl:$(Build.SourcesDirectory)\msbuild.binlog
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
      maximumCpuCount: true

# PowerToysSetupCustomActions.dll NEED TO BE SIGNED HERE

  - task: VSBuild@1
    displayName: Build PowerToysSetup
    inputs:
      solution: '**/installer/PowerToysSetup.sln'
      vsVersion: 16.0
      msbuildArgs: /p:CIBuild=true /bl:$(Build.SourcesDirectory)\msbuild.binlog
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      clean: true
      maximumCpuCount: true

# SETUP NEED TO BE SIGNED HERE

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: binlog'
    condition: failed()
    continueOnError: True
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)\msbuild.binlog
      ArtifactName: binlog-$(BuildPlatform)

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection

# COPYING NEEDS TO BE MOVED HIGHER
# IS THIS NEEDED REALLY?

  - task: CopyFiles@2
    displayName: Copy VideoConferenceProxyFilter_x86 to build output
    inputs: 
      sourceFolder: './x86/Release'
      Contents: >-
        'modules\VideoConference\VideoConferenceProxyFilter_x86.dll'
      TargetFolder: Build_Output
      OverWrite: true

# COPYING NEEDS TO BE MOVED HIGHER
# IS THIS NEEDED REALLY?

  - task: CopyFiles@2
    displayName: Copy core files to build output
    inputs: 
      sourceFolder: './x64/Release'
      Contents: >-
        'PowerToys.ActionRunner.exe'
        'PowerToys.Update.exe'
        'BackgroundActivatorDLL.dll'
        'Notifications.dll'
        'os-detection.dll'
        'PowerToys.exe'
        'PowerToysInterop.dll'
        'BugReportTool\BugReportTool.exe'
        '**\*.resources.dll'
        'modules\ColorPicker\ColorPicker.dll'
        'modules\ColorPicker\ColorPickerUI.dll'
        'modules\ColorPicker\ColorPickerUI.exe'
        'modules\ColorPicker\ManagedCommon.dll'
        'modules\ColorPicker\ManagedTelemetry.dll'
        'modules\ColorPicker\Microsoft.PowerToys.Common.UI.dll'
        'modules\ColorPicker\Microsoft.PowerToys.Settings.UI.Lib.dll'
        'modules\ColorPicker\PowerToysInterop.dll'
        'modules\ColorPicker\Telemetry.dll'
        '**\*.resources.dll'
        'modules\Awake\AwakeModuleInterface.dll'
        'modules\Awake\ManagedCommon.dll'
        'modules\Awake\ManagedTelemetry.dll'
        'modules\Awake\Microsoft.PowerToys.Settings.UI.Lib.dll'
        'modules\Awake\PowerToys.Awake.exe'
        'modules\Awake\PowerToys.Awake.dll'
        'modules\Awake\PowerToysInterop.dll'
        'modules\FancyZones\fancyzones.dll'
        'modules\FancyZones\FancyZonesEditor.exe'
        'modules\FancyZones\FancyZonesEditor.dll'
        'modules\FancyZones\FancyZonesModuleInterface.dll'
        'modules\FancyZones\ManagedCommon.dll'
        'modules\FancyZones\ManagedTelemetry.dll'
        'modules\FancyZones\PowerToys.FancyZones.exe'
        'modules\FancyZones\PowerToysInterop.dll'
        'modules\FancyZones\Telemetry.dll'
        'modules\FancyZones\Microsoft.PowerToys.Common.UI.dll'
        'modules\FileExplorerPreview\ManagedTelemetry.dll'
        'modules\FileExplorerPreview\MarkdownPreviewHandler.dll'
        'modules\FileExplorerPreview\MarkdownPreviewHandler.comhost.dll'
        'modules\FileExplorerPreview\PdfPreviewHandler.dll'
        'modules\FileExplorerPreview\PdfPreviewHandler.comhost.dll'
        'modules\FileExplorerPreview\PdfThumbnailProvider.dll'
        'modules\FileExplorerPreview\PdfThumbnailProvider.comhost.dll'
        'modules\FileExplorerPreview\powerpreview.dll'
        'modules\FileExplorerPreview\PreviewHandlerCommon.dll'
        'modules\FileExplorerPreview\SvgPreviewHandler.dll'
        'modules\FileExplorerPreview\SvgPreviewHandler.comhost.dll'
        'modules\FileExplorerPreview\SvgThumbnailProvider.dll'
        'modules\FileExplorerPreview\SvgThumbnailProvider.comhost.dll'
        'modules\FileExplorerPreview\Telemetry.dll'
        'modules\ImageResizer\ImageResizer.exe'
        'modules\ImageResizer\ImageResizer.dll'
        'modules\ImageResizer\ImageResizerExt.dll'
        'modules\ImageResizer\PowerToysInterop.dll'
        'modules\ImageResizer\ManagedCommon.dll'
        'modules\ImageResizer\ManagedTelemetry.dll'
        'modules\ImageResizer\Microsoft.PowerToys.Common.UI.dll'
        'modules\KeyboardManager\KeyboardManager.dll'
        'modules\KeyboardManager\KeyboardManagerEditor\PowerToys.KeyboardManagerEditor.exe'
        'modules\KeyboardManager\KeyboardManagerEngine\PowerToys.KeyboardManagerEngine.exe'
        'modules\launcher\Microsoft.PowerToys.Settings.UI.Lib.dll'
        'modules\launcher\ManagedCommon.dll'
        'modules\launcher\ManagedTelemetry.dll'
        'modules\launcher\Microsoft.PowerToys.Common.UI.dll'
        'modules\launcher\Microsoft.Launcher.dll'
        'modules\launcher\Plugins\Calculator\Microsoft.PowerToys.Run.Plugin.Calculator.dll'
        'modules\launcher\Plugins\Calculator\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Folder\Microsoft.Plugin.Folder.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Folder\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Indexer\Microsoft.Plugin.Indexer.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Indexer\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Program\Microsoft.Plugin.Program.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Program\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.PowerToys.Run.Plugin.Registry\Microsoft.PowerToys.Run.Plugin.Registry.dll'
        'modules\launcher\Plugins\Microsoft.PowerToys.Run.Plugin.Registry\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.PowerToys.Run.Plugin.WindowsSettings\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.PowerToys.Run.Plugin.WindowsSettings\Microsoft.PowerToys.Run.Plugin.WindowsSettings.dll'
        'modules\launcher\Plugins\Microsoft.PowerToys.Run.Plugin.WindowsSettings\WindowsSettings.json'
        'modules\launcher\Plugins\Microsoft.Plugin.Shell\Microsoft.Plugin.Shell.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Shell\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Uri\Microsoft.Plugin.Uri.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.Uri\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.WindowWalker\Microsoft.Plugin.WindowWalker.dll'
        'modules\launcher\Plugins\Microsoft.Plugin.WindowWalker\ManagedTelemetry.dll'
        'modules\launcher\Plugins\Community.UnitConverter\Community.PowerToys.Run.Plugin.UnitConverter.dll'
        'modules\launcher\Plugins\VSCodeWorkspaces\Community.PowerToys.Run.Plugin.VSCodeWorkspaces.dll'
        'modules\launcher\Plugins\Service\Microsoft.PowerToys.Run.Plugin.Service.dll'
        'modules\launcher\Plugins\System\Microsoft.PowerToys.Run.Plugin.System.dll'
        'modules\launcher\Plugins\WindowsTerminal\Microsoft.PowerToys.Run.Plugin.WindowsTerminal.dll'
        'modules\launcher\Plugins\WindowsTerminal\ManagedTelemetry.dll'
        'modules\launcher\PowerLauncher.dll'
        'modules\launcher\PowerLauncher.exe'
        'modules\launcher\PowerLauncher.Telemetry.dll'
        'modules\launcher\PowerLauncher.UI.exe'
        'modules\launcher\PowerToysInterop.dll'
        'modules\launcher\Telemetry.dll'
        'modules\launcher\Wox.dll'
        'modules\launcher\Wox.Infrastructure.dll'
        'modules\launcher\Wox.Plugin.dll'
        'modules\MouseUtils\FindMyMouse.dll'
        'modules\PowerRename\PowerRenameExt.dll'
        'modules\PowerRename\PowerRenameUILib.dll'
        'modules\PowerRename\PowerRename.exe'
        'modules\ShortcutGuide\ShortcutGuide\PowerToys.ShortcutGuide.exe'
        'modules\ShortcutGuide\ShortcutGuideModuleInterface\ShortcutGuideModuleInterface.dll'
        'modules\VideoConference\VideoConferenceModule.dll'
        'modules\VideoConference\VideoConferenceProxyFilter_x64.dll'
        'Settings\ManagedTelemetry.dll'
        'Settings\Microsoft.PowerToys.Settings.UI.exe'
        'Settings\Microsoft.PowerToys.Settings.UI.Lib.dll'
        'Settings\PowerToys.Settings.dll'
        'Settings\PowerToys.Settings.exe'
        'Settings\PowerToysInterop.dll'
        'Settings\Telemetry.dll'
        'Settings\ManagedCommon.dll'
      TargetFolder: Build_Output
      OverWrite: true

# DUSTIN: do we need build artifacts publishing?
  #- task: PublishBuildArtifacts@1
  #  displayName: TERMINAL LEGACY - Publish Artifact (appx)
  #  inputs:
  #    PathtoPublish: $(Build.ArtifactStagingDirectory)/appx
  #    ArtifactName: appx-$(BuildPlatform)-$(BuildConfiguration)

  #- task: PublishSymbols@2
  #  displayName: Publish symbols path
  #  continueOnError: True
  #  inputs:
  #    SearchPattern: '**/*.pdb'
  #    IndexSources: false
  #    SymbolServerType: TeamServices
  #- task: EsrpCodeSigning@1
  #  displayName: USE AS BASE BUT TERMINAL CODE - Submit *.msixbundle to ESRP for code signing
  #  inputs:
  #    ConnectedServiceName: 9d6d2960-0793-4d59-943e-78dcb434840a
  #    FolderPath: $(System.ArtifactsDirectory)
  #    Pattern: Microsoft.WindowsTerminal*.msixbundle
  #    UseMinimatch: true
  #    signConfigType: inlineSignParams
  #    inlineOperation: >-
  #      [
  #          {
  #              "KeyCode": "Dynamic",
  #              "CertTemplateName": "WINMSAPP1ST",
  #              "CertSubjectName": "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US",
  #              "OperationCode": "SigntoolSign",
  #              "Parameters": {
  #                  "OpusName": "Microsoft",
  #                  "OpusInfo": "http://www.microsoft.com",
  #                  "FileDigest": "/fd \"SHA256\"",
  #                  "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
  #              },
  #              "ToolName": "sign",
  #              "ToolVersion": "1.0"
  #          },
  #          {
  #              "KeyCode": "Dynamic",
  #              "CertTemplateName": "WINMSAPP1ST",
  #              "CertSubjectName": "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US",
  #              "OperationCode": "SigntoolVerify",
  #              "Parameters": {},
  #              "ToolName": "sign",
  #              "ToolVersion": "1.0"
  #          }
  #      ]
  #- task: PublishBuildArtifacts@1
  #  displayName: 'TERMINAL LEGACY - Publish Artifact: appxbundle-signed'
  #  inputs:
  #    PathtoPublish: $(System.ArtifactsDirectory)
  #    ArtifactName: appxbundle-signed
...
